services:
  - type: web
    name: task-manager-api
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres:feiNwnvRP8JAAjqt@db.kawjehjqhnxqhkjcgedz.supabase.co:5432/postgres?pgbouncer=true&connection_limit=1"
      - key: DIRECT_URL
        value: "postgresql://postgres:feiNwnvRP8JAAjqt@db.kawjehjqhnxqhkjcgedz.supabase.co:5432/postgres?sslmode=require" 